# Generated by Django 4.2.3 on 2023-09-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='card',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
