# Generated by Django 4.2.3 on 2023-09-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0002_alter_cartitem_card_alter_cartitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='card',
            new_name='id_carta',
        ),
    ]
