# Generated by Django 4.2.3 on 2023-09-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0003_rename_card_cartitem_id_carta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='nombre_carta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
